# Auto-generated from Nikkei 225 constituent research (indexes.nikkei.co.jp, 2026-08-14 update).
# code: 4-char JPX securities code, name: official constituent name, sector: Nikkei industry classification.
NIKKEI225 = [
    {'code': '1332', 'name': 'NISSUI CORP.', 'sector': 'Fishery'},
    {'code': '1605', 'name': 'INPEX CORP.', 'sector': 'Mining'},
    {'code': '1721', 'name': 'COMSYS HOLDINGS CORP.', 'sector': 'Construction'},
    {'code': '1801', 'name': 'TAISEI CORP.', 'sector': 'Construction'},
    {'code': '1802', 'name': 'OBAYASHI CORP.', 'sector': 'Construction'},
    {'code': '1803', 'name': 'SHIMIZU CORP.', 'sector': 'Construction'},
    {'code': '1808', 'name': 'HASEKO CORP.', 'sector': 'Construction'},
    {'code': '1812', 'name': 'KAJIMA CORP.', 'sector': 'Construction'},
    {'code': '1925', 'name': 'DAIWA HOUSE IND. CO., LTD.', 'sector': 'Construction'},
    {'code': '1928', 'name': 'SEKISUI HOUSE, LTD.', 'sector': 'Construction'},
    {'code': '1963', 'name': 'JGC HOLDINGS CORP.', 'sector': 'Construction'},
    {'code': '2002', 'name': 'NISSHIN SEIFUN GROUP INC.', 'sector': 'Foods'},
    {'code': '2269', 'name': 'MEIJI HOLDINGS CO., LTD.', 'sector': 'Foods'},
    {'code': '2282', 'name': 'NH FOODS LTD.', 'sector': 'Foods'},
    {'code': '2413', 'name': 'M3, INC.', 'sector': 'Services'},
    {'code': '2432', 'name': 'DENA CO., LTD.', 'sector': 'Services'},
    {'code': '2501', 'name': 'SAPPORO BREWERIES LTD.', 'sector': 'Foods'},
    {'code': '2502', 'name': 'ASAHI GROUP HOLDINGS, LTD.', 'sector': 'Foods'},
    {'code': '2503', 'name': 'KIRIN HOLDINGS CO., LTD.', 'sector': 'Foods'},
    {'code': '2768', 'name': 'SOJITZ CORP.', 'sector': 'Trading Companies'},
    {'code': '2801', 'name': 'KIKKOMAN CORP.', 'sector': 'Foods'},
    {'code': '2802', 'name': 'AJINOMOTO CO., INC.', 'sector': 'Foods'},
    {'code': '285A', 'name': 'KIOXIA HOLDINGS CORP.', 'sector': 'Electric Machinery'},
    {'code': '2871', 'name': 'NICHIREI CORP.', 'sector': 'Foods'},
    {'code': '2914', 'name': 'JAPAN TOBACCO INC.', 'sector': 'Foods'},
    {'code': '3086', 'name': 'J.FRONT RETAILING CO., LTD.', 'sector': 'Retail'},
    {'code': '3092', 'name': 'ZOZO, INC.', 'sector': 'Retail'},
    {'code': '3099', 'name': 'ISETAN MITSUKOSHI HOLDINGS LTD.', 'sector': 'Retail'},
    {'code': '3289', 'name': 'TOKYU FUDOSAN HOLDINGS CORP.', 'sector': 'Real Estate'},
    {'code': '3382', 'name': 'SEVEN & I HOLDINGS CO., LTD.', 'sector': 'Retail'},
    {'code': '3401', 'name': 'TEIJIN LTD.', 'sector': 'Textiles & Apparel'},
    {'code': '3402', 'name': 'TORAY INDUSTRIES, INC.', 'sector': 'Textiles & Apparel'},
    {'code': '3405', 'name': 'KURARAY CO., LTD.', 'sector': 'Chemicals'},
    {'code': '3407', 'name': 'ASAHI KASEI CORP.', 'sector': 'Chemicals'},
    {'code': '3436', 'name': 'SUMCO CORP.', 'sector': 'Nonferrous Metals'},
    {'code': '3659', 'name': 'NEXON CO., LTD.', 'sector': 'Services'},
    {'code': '3697', 'name': 'SHIFT INC.', 'sector': 'Services'},
    {'code': '3861', 'name': 'OJI HOLDINGS CORP.', 'sector': 'Pulp & Paper'},
    {'code': '4004', 'name': 'RESONAC HOLDINGS CORP.', 'sector': 'Chemicals'},
    {'code': '4005', 'name': 'SUMITOMO CHEMICAL CO., LTD.', 'sector': 'Chemicals'},
    {'code': '4021', 'name': 'NISSAN CHEMICAL CORP.', 'sector': 'Chemicals'},
    {'code': '4042', 'name': 'TOSOH CORP.', 'sector': 'Chemicals'},
    {'code': '4043', 'name': 'TOKUYAMA CORP.', 'sector': 'Chemicals'},
    {'code': '4061', 'name': 'DENKA CO., LTD.', 'sector': 'Chemicals'},
    {'code': '4062', 'name': 'IBIDEN CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '4063', 'name': 'SHIN-ETSU CHEMICAL CO., LTD.', 'sector': 'Chemicals'},
    {'code': '4151', 'name': 'KYOWA KIRIN CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4183', 'name': 'MITSUI CHEMICALS, INC.', 'sector': 'Chemicals'},
    {'code': '4188', 'name': 'MITSUBISHI CHEMICAL GROUP CORP.', 'sector': 'Chemicals'},
    {'code': '4208', 'name': 'UBE CORP.', 'sector': 'Chemicals'},
    {'code': '4307', 'name': 'NOMURA RESEARCH INSTITUTE, LTD.', 'sector': 'Services'},
    {'code': '4324', 'name': 'DENTSU GROUP INC.', 'sector': 'Services'},
    {'code': '4385', 'name': 'MERCARI, INC.', 'sector': 'Services'},
    {'code': '4452', 'name': 'KAO CORP.', 'sector': 'Chemicals'},
    {'code': '4502', 'name': 'TAKEDA PHARMACEUTICAL CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4503', 'name': 'ASTELLAS PHARMA INC.', 'sector': 'Pharmaceuticals'},
    {'code': '4506', 'name': 'SUMITOMO PHARMA CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4507', 'name': 'SHIONOGI & CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4519', 'name': 'CHUGAI PHARMACEUTICAL CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4523', 'name': 'EISAI CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4543', 'name': 'TERUMO CORP.', 'sector': 'Precision Instruments'},
    {'code': '4568', 'name': 'DAIICHI SANKYO CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4578', 'name': 'OTSUKA HOLDINGS CO., LTD.', 'sector': 'Pharmaceuticals'},
    {'code': '4661', 'name': 'ORIENTAL LAND CO., LTD.', 'sector': 'Services'},
    {'code': '4689', 'name': 'LY CORP.', 'sector': 'Services'},
    {'code': '4704', 'name': 'TREND MICRO INC.', 'sector': 'Services'},
    {'code': '4751', 'name': 'CYBERAGENT, INC.', 'sector': 'Services'},
    {'code': '4755', 'name': 'RAKUTEN GROUP, INC.', 'sector': 'Services'},
    {'code': '4901', 'name': 'FUJIFILM HOLDINGS CORP.', 'sector': 'Chemicals'},
    {'code': '4902', 'name': 'KONICA MINOLTA, INC.', 'sector': 'Precision Instruments'},
    {'code': '4911', 'name': 'SHISEIDO CO., LTD.', 'sector': 'Chemicals'},
    {'code': '5019', 'name': 'IDEMITSU KOSAN CO., LTD.', 'sector': 'Petroleum'},
    {'code': '5020', 'name': 'ENEOS HOLDINGS, INC.', 'sector': 'Petroleum'},
    {'code': '5101', 'name': 'THE YOKOHAMA RUBBER CO., LTD.', 'sector': 'Rubber'},
    {'code': '5108', 'name': 'BRIDGESTONE CORP.', 'sector': 'Rubber'},
    {'code': '5201', 'name': 'AGC INC.', 'sector': 'Glass & Ceramics'},
    {'code': '5214', 'name': 'NIPPON ELECTRIC GLASS CO., LTD.', 'sector': 'Glass & Ceramics'},
    {'code': '5233', 'name': 'TAIHEIYO CEMENT CORP.', 'sector': 'Glass & Ceramics'},
    {'code': '5301', 'name': 'TOKAI CARBON CO., LTD.', 'sector': 'Glass & Ceramics'},
    {'code': '5332', 'name': 'TOTO LTD.', 'sector': 'Glass & Ceramics'},
    {'code': '5333', 'name': 'NGK CORP.', 'sector': 'Glass & Ceramics'},
    {'code': '5401', 'name': 'NIPPON STEEL CORP.', 'sector': 'Steel'},
    {'code': '5406', 'name': 'KOBE STEEL, LTD.', 'sector': 'Steel'},
    {'code': '5411', 'name': 'JFE HOLDINGS, INC.', 'sector': 'Steel'},
    {'code': '543A', 'name': 'ARCHION CORP.', 'sector': 'Automobiles & Auto parts'},
    {'code': '5631', 'name': 'THE JAPAN STEEL WORKS, LTD.', 'sector': 'Machinery'},
    {'code': '5706', 'name': 'MITSUI KINZOKU CO., LTD.', 'sector': 'Nonferrous Metals'},
    {'code': '5711', 'name': 'MITSUBISHI MATERIALS CORP.', 'sector': 'Nonferrous Metals'},
    {'code': '5713', 'name': 'SUMITOMO METAL MINING CO., LTD.', 'sector': 'Nonferrous Metals'},
    {'code': '5714', 'name': 'DOWA HOLDINGS CO., LTD.', 'sector': 'Nonferrous Metals'},
    {'code': '5801', 'name': 'FURUKAWA ELECTRIC CO., LTD.', 'sector': 'Nonferrous Metals'},
    {'code': '5802', 'name': 'SUMITOMO ELECTRIC IND., LTD.', 'sector': 'Nonferrous Metals'},
    {'code': '5803', 'name': 'FUJIKURA LTD.', 'sector': 'Nonferrous Metals'},
    {'code': '5831', 'name': 'SHIZUOKA FINANCIAL GROUP, INC.', 'sector': 'Banking'},
    {'code': '6098', 'name': 'RECRUIT HOLDINGS CO., LTD.', 'sector': 'Services'},
    {'code': '6103', 'name': 'OKUMA CORP.', 'sector': 'Machinery'},
    {'code': '6113', 'name': 'AMADA CO., LTD.', 'sector': 'Machinery'},
    {'code': '6146', 'name': 'DISCO CORP.', 'sector': 'Precision Instruments'},
    {'code': '6178', 'name': 'JAPAN POST HOLDINGS CO., LTD.', 'sector': 'Services'},
    {'code': '6273', 'name': 'SMC CORP.', 'sector': 'Machinery'},
    {'code': '6301', 'name': 'KOMATSU LTD.', 'sector': 'Machinery'},
    {'code': '6302', 'name': 'SUMITOMO HEAVY IND., LTD.', 'sector': 'Machinery'},
    {'code': '6305', 'name': 'HITACHI CONST. MACH. CO., LTD.', 'sector': 'Machinery'},
    {'code': '6326', 'name': 'KUBOTA CORP.', 'sector': 'Machinery'},
    {'code': '6361', 'name': 'EBARA CORP.', 'sector': 'Machinery'},
    {'code': '6367', 'name': 'DAIKIN INDUSTRIES, LTD.', 'sector': 'Machinery'},
    {'code': '6471', 'name': 'NSK LTD.', 'sector': 'Machinery'},
    {'code': '6472', 'name': 'NTN CORP.', 'sector': 'Machinery'},
    {'code': '6473', 'name': 'JTEKT CORP.', 'sector': 'Machinery'},
    {'code': '6479', 'name': 'MINEBEA MITSUMI INC.', 'sector': 'Electric Machinery'},
    {'code': '6501', 'name': 'HITACHI, LTD.', 'sector': 'Electric Machinery'},
    {'code': '6503', 'name': 'MITSUBISHI ELECTRIC CORP.', 'sector': 'Electric Machinery'},
    {'code': '6504', 'name': 'FUJI ELECTRIC CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '6506', 'name': 'YASKAWA ELECTRIC CORP.', 'sector': 'Electric Machinery'},
    {'code': '6526', 'name': 'SOCIONEXT INC.', 'sector': 'Electric Machinery'},
    {'code': '6532', 'name': 'BAYCURRENT, INC.', 'sector': 'Services'},
    {'code': '6645', 'name': 'OMRON CORP.', 'sector': 'Electric Machinery'},
    {'code': '6701', 'name': 'NEC CORP.', 'sector': 'Electric Machinery'},
    {'code': '6702', 'name': 'FUJITSU LTD.', 'sector': 'Electric Machinery'},
    {'code': '6723', 'name': 'RENESAS ELECTRONICS CORP.', 'sector': 'Electric Machinery'},
    {'code': '6724', 'name': 'SEIKO EPSON CORP.', 'sector': 'Electric Machinery'},
    {'code': '6752', 'name': 'PANASONIC HOLDINGS CORP.', 'sector': 'Electric Machinery'},
    {'code': '6753', 'name': 'SHARP CORP.', 'sector': 'Electric Machinery'},
    {'code': '6758', 'name': 'SONY GROUP CORP.', 'sector': 'Electric Machinery'},
    {'code': '6762', 'name': 'TDK CORP.', 'sector': 'Electric Machinery'},
    {'code': '6770', 'name': 'ALPS ALPINE CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '6841', 'name': 'YOKOGAWA ELECTRIC CORP.', 'sector': 'Electric Machinery'},
    {'code': '6857', 'name': 'ADVANTEST CORP.', 'sector': 'Electric Machinery'},
    {'code': '6861', 'name': 'KEYENCE CORP.', 'sector': 'Electric Machinery'},
    {'code': '6902', 'name': 'DENSO CORP.', 'sector': 'Electric Machinery'},
    {'code': '6920', 'name': 'LASERTEC CORP.', 'sector': 'Electric Machinery'},
    {'code': '6954', 'name': 'FANUC CORP.', 'sector': 'Electric Machinery'},
    {'code': '6963', 'name': 'ROHM CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '6971', 'name': 'KYOCERA CORP.', 'sector': 'Electric Machinery'},
    {'code': '6976', 'name': 'TAIYO YUDEN CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '6981', 'name': 'MURATA MANUFACTURING CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '6988', 'name': 'NITTO DENKO CORP.', 'sector': 'Chemicals'},
    {'code': '7004', 'name': 'KANADEVIA CORP.', 'sector': 'Machinery'},
    {'code': '7011', 'name': 'MITSUBISHI HEAVY IND., LTD.', 'sector': 'Machinery'},
    {'code': '7012', 'name': 'KAWASAKI HEAVY IND., LTD.', 'sector': 'Shipbuilding'},
    {'code': '7013', 'name': 'IHI CORP.', 'sector': 'Machinery'},
    {'code': '7186', 'name': 'YOKOHAMA FINANCIAL GROUP, INC.', 'sector': 'Banking'},
    {'code': '7201', 'name': 'NISSAN MOTOR CO., LTD.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7202', 'name': 'ISUZU MOTORS LTD.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7203', 'name': 'TOYOTA MOTOR CORP.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7211', 'name': 'MITSUBISHI MOTORS CORP.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7261', 'name': 'MAZDA MOTOR CORP.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7267', 'name': 'HONDA MOTOR CO., LTD.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7269', 'name': 'SUZUKI MOTOR CORP.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7270', 'name': 'SUBARU CORP.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7272', 'name': 'YAMAHA MOTOR CO., LTD.', 'sector': 'Automobiles & Auto parts'},
    {'code': '7453', 'name': 'RYOHIN KEIKAKU CO., LTD.', 'sector': 'Retail'},
    {'code': '7532', 'name': 'PAN PACIFIC INTERNATIONAL HOLDINGS CORP.', 'sector': 'Retail'},
    {'code': '7731', 'name': 'NIKON CORP.', 'sector': 'Precision Instruments'},
    {'code': '7733', 'name': 'OLYMPUS CORP.', 'sector': 'Precision Instruments'},
    {'code': '7735', 'name': 'SCREEN HOLDINGS CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '7741', 'name': 'HOYA CORP.', 'sector': 'Precision Instruments'},
    {'code': '7751', 'name': 'CANON INC.', 'sector': 'Electric Machinery'},
    {'code': '7752', 'name': 'RICOH CO., LTD.', 'sector': 'Electric Machinery'},
    {'code': '7832', 'name': 'BANDAI NAMCO HOLDINGS INC.', 'sector': 'Other Manufacturing'},
    {'code': '7911', 'name': 'TOPPAN HOLDINGS INC.', 'sector': 'Other Manufacturing'},
    {'code': '7912', 'name': 'DAI NIPPON PRINTING CO., LTD.', 'sector': 'Other Manufacturing'},
    {'code': '7951', 'name': 'YAMAHA CORP.', 'sector': 'Other Manufacturing'},
    {'code': '7974', 'name': 'NINTENDO CO., LTD.', 'sector': 'Services'},
    {'code': '8001', 'name': 'ITOCHU CORP.', 'sector': 'Trading Companies'},
    {'code': '8002', 'name': 'MARUBENI CORP.', 'sector': 'Trading Companies'},
    {'code': '8015', 'name': 'TOYOTA TSUSHO CORP.', 'sector': 'Trading Companies'},
    {'code': '8031', 'name': 'MITSUI & CO., LTD.', 'sector': 'Trading Companies'},
    {'code': '8035', 'name': 'TOKYO ELECTRON LTD.', 'sector': 'Electric Machinery'},
    {'code': '8053', 'name': 'SUMITOMO CORP.', 'sector': 'Trading Companies'},
    {'code': '8058', 'name': 'MITSUBISHI CORP.', 'sector': 'Trading Companies'},
    {'code': '8233', 'name': 'TAKASHIMAYA CO., LTD.', 'sector': 'Retail'},
    {'code': '8252', 'name': 'MARUI GROUP CO., LTD.', 'sector': 'Retail'},
    {'code': '8253', 'name': 'CREDIT SAISON CO., LTD.', 'sector': 'Other Financial Services'},
    {'code': '8267', 'name': 'AEON CO., LTD.', 'sector': 'Retail'},
    {'code': '8304', 'name': 'AOZORA BANK, LTD.', 'sector': 'Banking'},
    {'code': '8306', 'name': 'MITSUBISHI UFJ FINANCIAL GROUP, INC.', 'sector': 'Banking'},
    {'code': '8308', 'name': 'RESONA HOLDINGS, INC.', 'sector': 'Banking'},
    {'code': '8309', 'name': 'SUMITOMO MITSUI TRUST GROUP, INC.', 'sector': 'Banking'},
    {'code': '8316', 'name': 'SUMITOMO MITSUI FINANCIAL GROUP, INC.', 'sector': 'Banking'},
    {'code': '8331', 'name': 'THE CHIBA BANK, LTD.', 'sector': 'Banking'},
    {'code': '8354', 'name': 'FUKUOKA FINANCIAL GROUP, INC.', 'sector': 'Banking'},
    {'code': '8411', 'name': 'MIZUHO FINANCIAL GROUP, INC.', 'sector': 'Banking'},
    {'code': '8591', 'name': 'ORIX CORP.', 'sector': 'Other Financial Services'},
    {'code': '8601', 'name': 'DAIWA SECURITIES GROUP INC.', 'sector': 'Securities'},
    {'code': '8604', 'name': 'NOMURA HOLDINGS, INC.', 'sector': 'Securities'},
    {'code': '8630', 'name': 'SOMPO HOLDINGS, INC.', 'sector': 'Insurance'},
    {'code': '8697', 'name': 'JAPAN EXCHANGE GROUP, INC.', 'sector': 'Other Financial Services'},
    {'code': '8725', 'name': 'MS&AD INSURANCE GROUP HOLDINGS, INC.', 'sector': 'Insurance'},
    {'code': '8750', 'name': 'DAIICHI LIFE GROUP, INC.', 'sector': 'Insurance'},
    {'code': '8766', 'name': 'TOKIO MARINE HOLDINGS, INC.', 'sector': 'Insurance'},
    {'code': '8795', 'name': 'T&D HOLDINGS, INC.', 'sector': 'Insurance'},
    {'code': '8801', 'name': 'MITSUI FUDOSAN CO., LTD.', 'sector': 'Real Estate'},
    {'code': '8802', 'name': 'MITSUBISHI ESTATE CO., LTD.', 'sector': 'Real Estate'},
    {'code': '8804', 'name': 'TOKYO TATEMONO CO., LTD.', 'sector': 'Real Estate'},
    {'code': '8830', 'name': 'SUMITOMO REALTY & DEVELOPMENT CO., LTD.', 'sector': 'Real Estate'},
    {'code': '9001', 'name': 'TOBU RAILWAY CO., LTD.', 'sector': 'Railway & Bus'},
    {'code': '9005', 'name': 'TOKYU CORP.', 'sector': 'Railway & Bus'},
    {'code': '9007', 'name': 'ODAKYU ELECTRIC RAILWAY CO., LTD.', 'sector': 'Railway & Bus'},
    {'code': '9008', 'name': 'KEIO CORP.', 'sector': 'Railway & Bus'},
    {'code': '9009', 'name': 'KEISEI ELECTRIC RAILWAY CO., LTD.', 'sector': 'Railway & Bus'},
    {'code': '9020', 'name': 'EAST JAPAN RAILWAY CO.', 'sector': 'Railway & Bus'},
    {'code': '9021', 'name': 'WEST JAPAN RAILWAY CO.', 'sector': 'Railway & Bus'},
    {'code': '9022', 'name': 'CENTRAL JAPAN RAILWAY CO., LTD.', 'sector': 'Railway & Bus'},
    {'code': '9064', 'name': 'YAMATO HOLDINGS CO., LTD.', 'sector': 'Land Transport'},
    {'code': '9101', 'name': 'NIPPON YUSEN K.K.', 'sector': 'Marine Transport'},
    {'code': '9104', 'name': 'MITSUI O.S.K.LINES, LTD.', 'sector': 'Marine Transport'},
    {'code': '9107', 'name': 'KAWASAKI KISEN KAISHA, LTD.', 'sector': 'Marine Transport'},
    {'code': '9147', 'name': 'NIPPON EXPRESS HOLDINGS, INC.', 'sector': 'Land Transport'},
    {'code': '9201', 'name': 'JAPAN AIRLINES CO., LTD.', 'sector': 'Air Transport'},
    {'code': '9202', 'name': 'ANA HOLDINGS INC.', 'sector': 'Air Transport'},
    {'code': '9432', 'name': 'NTT, INC.', 'sector': 'Communications'},
    {'code': '9433', 'name': 'KDDI CORP.', 'sector': 'Communications'},
    {'code': '9434', 'name': 'SOFTBANK CORP.', 'sector': 'Communications'},
    {'code': '9501', 'name': 'TOKYO ELECTRIC POWER COMPANY HOLDINGS, INC.', 'sector': 'Electric Power'},
    {'code': '9502', 'name': 'CHUBU ELECTRIC POWER CO., INC.', 'sector': 'Electric Power'},
    {'code': '9503', 'name': 'THE KANSAI ELECTRIC POWER CO., INC.', 'sector': 'Electric Power'},
    {'code': '9531', 'name': 'TOKYO GAS CO., LTD.', 'sector': 'Gas'},
    {'code': '9532', 'name': 'OSAKA GAS CO., LTD.', 'sector': 'Gas'},
    {'code': '9602', 'name': 'TOHO CO., LTD', 'sector': 'Services'},
    {'code': '9735', 'name': 'SECOM CO., LTD.', 'sector': 'Services'},
    {'code': '9766', 'name': 'KONAMI GROUP CORP.', 'sector': 'Services'},
    {'code': '9843', 'name': 'NITORI HOLDINGS CO., LTD.', 'sector': 'Retail'},
    {'code': '9983', 'name': 'FAST RETAILING CO., LTD.', 'sector': 'Retail'},
    {'code': '9984', 'name': 'SOFTBANK GROUP CORP.', 'sector': 'Communications'},
]
